### ISSUE TITLE
Links & Routing

### ISSUE THREAD

**Issue by ondryice** [ondryice/wildfire-safety#22]
Set up react routing, so that different pages can have different URL endpoints

- [ ] NavbarButton should link to different endpoints
- [ ] Page should render different content based on the URL endpoint
- [ ] Links to the site should navigate to the proper page
