### ISSUE TITLE
About page

### ISSUE THREAD

**Issue by ondryice** [ondryice/wildfire-safety#24]
Should have info on the dev team and product owner

- [ ] Card components that contain basic info on the associated team member
- [ ] Responsive design: *does it look ok on mobile?*
- [ ] Ease of navigation: is it a modal, can I get out of it easily, is it an entirely separate page, can I use the back arrow or do I use a close / esc button?
