### ISSUE TITLE
Navbar component

### ISSUE THREAD

**Issue by ondryice** [ondryice/wildfire-safety#6]
- [x] add component to hierarchy
- [x] skeletal structure of navbar
- [x] navbar button component
- [x] populate navbar (should be easily configured with navbar items)
